# Generated by Django 3.0.3 on 2020-04-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='name',
        ),
    ]
