# Generated by Django 3.0.8 on 2020-07-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_area_author_commentary_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['data__name']},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['data__name']},
        ),
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['data__title']},
        ),
    ]
