# Generated by Django 3.0.7 on 2020-10-26 08:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20200731_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Characters',
                'ordering': ['data__name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Places',
                'ordering': ['data__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['data__name'], 'verbose_name_plural': 'Commentaries'},
        ),
    ]
