# Generated by Django 3.0.7 on 2020-12-01 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0009_auto_20201201_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='commentary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Commentary'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
