# Generated by Django 3.0.7 on 2020-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_auto_20201201_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='commentary',
            field=models.CharField(max_length=100),
        ),
    ]
