# Generated by Django 3.0.7 on 2021-02-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_auto_20201201_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annotation',
            new_name='Lemma',
        ),
        migrations.RenameModel(
            old_name='Commentary',
            new_name='Library',
        ),
        migrations.RenameModel(
            old_name='Area',
            new_name='Work',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['data__name'], 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['data__title']},
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
