# Generated by Django 3.0.7 on 2021-02-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0012_auto_20210211_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
