# Generated by Django 3.0.7 on 2021-03-23 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0013_auto_20210211_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Topographies',
                'ordering': ['data__name'],
            },
        ),
    ]
