# Generated by Django 3.0.4 on 2021-05-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['data__name'], 'verbose_name_plural': 'Libraries'},
        ),
    ]
