# Generated by Django 3.0.7 on 2021-05-31 15:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Sources',
                'ordering': ['data__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['data__name'], 'verbose_name_plural': 'Libraries'},
        ),
    ]
