# Generated by Django 3.0.4 on 2021-07-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_auto_20210503_1642'),
        ('annotation', '0016_auto_20210531_1511'),
    ]

    operations = [
    ]
