# Generated by Django 3.2.9 on 2022-01-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0017_merge_20210702_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topography',
        ),
    ]
